### ISSUE TITLE
Html.CspScriptNonce() without Core

### ISSUE THREAD

**Issue by soatley** [NWebsec/NWebsec#101]
Is there a way to use the `@Html.CspScriptNonce()` without using ASP.NET Core?  I'm still using the 4.6.1 framework.  In this case, I'd like to be able to insert the `nonce`  hash into inline scripts that are on the page automatically.

If this can't be done using the HTML Helper, is there a way I can get nonce's to work with NWebSec?

**Comment by klings** [comment]
Sure, it's in the ASP.NET 4 docs: https://docs.nwebsec.com/en/aspnet4/nwebsec/Configuring-csp.html#script-and-style-nonces-through-htmlhelpers

The HtmlHelpers are replaced with tag helpers in ASP.NET Core.

**Comment by soatley** [comment]
I've tried adding the the HtmlHelper code but it returns the following error:

CS1061 C# 'HtmlHelper<dynamic>' does not contain a definition for and no extension method accepting a first argument of type 'HtmlHelper<dynamic>' could be found (are you missing a using directive or an assembly reference?)

Perhaps I'm missing something in the documentation that I'm not implementing properly.

**Comment by klings** [comment]
Oh, you're probably missing the using directive. I've updated the docs, see if that helps.

**Comment by soatley** [comment]
Thank you, that was exactly it.  Everything works perfectly now.
