### ISSUE TITLE
 Could not load file or assembly 'NWebsec, Version=4.3.0.0, Culture=neutral, PublicKeyToken=3613da5f958908a1' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by phatcher** [NWebsec/NWebsec#102]
Loaded NWebSec.Mvc into the project and the project fails to start..

C:\Program Files (x86)\IIS Express\mscorlib.pdb: Cannot find or open the PDB file.
C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.pdb: Cannot find or open the PDB file.
C:\WINDOWS\mscorlib.pdb: Cannot find or open the PDB file.
C:\WINDOWS\symbols\dll\mscorlib.pdb: Cannot find or open the PDB file.
C:\WINDOWS\dll\mscorlib.pdb: Cannot find or open the PDB file.

Assemblies are referenced in the project which is targeting .NET 4.6.2 - odd thing is that it seems to be trying to mscorlib from 4.7  -> 4,7.2046.0 built by NET47REL1

**Comment by phatcher** [comment]
The issue is due to having a web with an api that is a virtual application - I hadn't installed NWebSec in the api, so it couldn't find the assembly.

Once I did that, I now get an error 500 from the API - I've tried the usual tricks of removing and re-adding the module in the child web.config but no joy

**Comment by klings** [comment]
I know people are running NWebsec in virtual applications which inherit a "root" web.config, so there's no known issues related to that setup. What's the exact error causing the 500?
