### ISSUE TITLE
Backporting to MVC version

### ISSUE THREAD

**Issue by phatcher** [NWebsec/NWebsec#103]
Would you accept pull requests bringing back features from the AspNet Core to the ASP.NET version - I can see myself being on ASP.NET for another 2 years until the Core ecosystem fleshes out more

**Comment by klings** [comment]
After considering this issue for a while I've landed on bringing the ASP.NET 4 projects to the new build system, and maintain them alongside the new libraries. After all, they still have more downloads than the core packages. This is the next big thing in my backlog, once that's done I'll start adding features again. So no need to attempt any backporting.
