### ISSUE TITLE
Strong Name Signed version

### ISSUE THREAD

**Issue by Astimus** [NWebsec/NWebsec#105]
After signing your libraries with https://github.com/MyGet/webhooks-sign-package they doesn't work. Can you create strong name signed version of your library?

**Comment by klings** [comment]
The ASP.NET 4 libraries are strong named. You mean the ASP.NET Core ones?

**Comment by Astimus** [comment]
@klings I forget to write. Yes, ASP.NET Core one) Is it possible to create signed version?

**Comment by Astimus** [comment]
@klings I use this two nuget packages: NWebsec.AspNetCore.Middleware, NWebsec.AspNetCore.Core. And all my unsigned librarys signed thru webhook sign server. But there are problems with this two. I don't understand why...

**Comment by mchender** [comment]
@klings any progress on creating strong named versions for the ASP.NET Core packages?

**Comment by klings** [comment]
No plans to strong name the ASP.NET Core packages. Why are you strong naming your ASP.NET Core applications/libraries? I thought this was a thing of the past.

**Comment by klings** [comment]
MSFT recommendation is to strong name shared libraries.

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

I will make it so.
