### ISSUE TITLE
Automatically generating NWebsecSessionAuthenticationKey at application start

### ISSUE THREAD

**Issue by etm-admin** [NWebsec/NWebsec#108]
Having NWebsecSessionAuthenticationKey manually defined is problematic when distributing applications as packages. Hardcoding is a bad option, explaining users they need to do it is also not ideal. 

Could it be automatically generated at application startup if the value is not present? Or would it be possible to manually set it using code?

**Comment by klings** [comment]
Sorry, the NWebsec session authentication library is no longer a priority. It's considered stable and bug free, and there won't be added any more features to it.
