### ISSUE TITLE
X-Frame-Options Allow-From?

### ISSUE THREAD

**Issue by escar** [NWebsec/NWebsec#109]
Why isn't it possible to configure [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)  header with 'ALLOW-FROM'?

Just have the `Deny` and `SameOrigin` options.

Cheers.

**Comment by nmg196** [comment]
I need this too.

**Comment by AshleyPoole** [comment]
@klings is this something you'd consider adding?

**Comment by klings** [comment]
You should probably use CSP [frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) instead. It works consistently across browsers, checks all ancestors (=more secure), and also lets you specify one or more ancestors if you need to.

I just checked my Chrome, it doesn't support `allow-from` according to: https://erlend.oftedal.no/blog/tools/xframeoptions/. So browser support is still flaky.

Let me know if there is any reason you can't solve this with CSP, else we can close the issue.

**Comment by anupshah** [comment]
According to here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors IE doesn't support this at all, and we still (sadly) have to support IE. IE does support allow-from in x-frame-options though, so having that would be the best of all worlds I think?
