### ISSUE TITLE
The name 'Source' does not exist in the current context

### ISSUE THREAD

**Issue by arc95** [NWebsec/NWebsec#111]
Thanks for this great library. I'm following the steps from [this page](https://docs.nwebsec.com/en/aspnet4/nwebsec/NWebsec.Mvc.html) to add global filters. However, I'm getting an error on a few of the filters that use `Source`:

```csharp
filters.Add(new CspDefaultSrcAttribute { Self = Source.Enable });
filters.Add(new CspScriptSrcAttribute { Self = Source.Enable });
//CSPReportOnly
filters.Add(new CspReportOnlyAttribute());
filters.Add(new CspScriptSrcReportOnlyAttribute { None = Source.Enable });
```

The above references to `Source` generates the following error:
```
The name 'Source' does not exist in the current context
```

For now, I've set all three to `true`. Thanks.

**Comment by klings** [comment]
Oh, that’s probably a bug in the docs. Try setting it to true instead.

**Comment by arc95** [comment]
Yup, did that and it's happy.
