### ISSUE TITLE
Generating nonces in MVC

### ISSUE THREAD

**Issue by arc95** [NWebsec/NWebsec#112]
How do you generate nonces for inline script tags? This example seems to be only for .NET Core while I'm using .NET 4.6:

```javascript
<script nws-csp-add-nonce="true">document.write("Hello world")</script>
```
Any solution for non-Core users? Thanks.

**Comment by klings** [comment]
Yes, there are HtmlHelpers for ASP.NET 4, you should find them too in the docs.

**Comment by arc95** [comment]
Thanks, @klings! Found this and it does the job: `@Html.CspScriptNonce()`
