### ISSUE TITLE
Should requirePermission be true?

### ISSUE THREAD

**Issue by arc95** [NWebsec/NWebsec#116]
Hi @klings. Found this setting in Web.config:

```xml
<sectionGroup name="nwebsec">
    <!-- For information on how to configure NWebsec please visit: https://docs.nwebsec.com/ -->
    <section name="httpHeaderSecurityModule" 
        type="NWebsec.Modules.Configuration.HttpHeaderSecurityConfigurationSection, NWebsec, Version=4.3.0.0, Culture=neutral, PublicKeyToken=3613da5f958908a1" 
        requirePermission="false" />
</sectionGroup>
```

When would we set the `requirePermission` flag to true?

**Comment by klings** [comment]
Never. This was related to the good ol' trust levels for ASP.NET applications, which turned out to be dead by design. You can find a short description of it here: https://msdn.microsoft.com/en-us/library/system.configuration.sectioninformation.requirepermission.aspx
