### ISSUE TITLE
Add Referrer-Policy via web.config

### ISSUE THREAD

**Issue by Matheis92** [NWebsec/NWebsec#118]
Hi @klings,

is there possible way or will it ever be possible to configure Referrer-Policy in the nwebsec section of the web.config of asp.net projects?

King Regards

**Comment by klings** [comment]
Yes, I'm currently aligning the "old" and "new" NWebsec version so they (mostly) contain the same features. In version 5, Referrer-Policy will also be part of the classic "NWebsec" package.

**Comment by klings** [comment]
Released.
