### ISSUE TITLE
.NET Core 2.0 support

### ISSUE THREAD

**Issue by programmersommer** [NWebsec/NWebsec#119]
When I trying to install package into just created .NET Core 2.0 application I am getting exception that:
"Package 'NWebsec 4.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project"

Something wrong with configuration on my machine or as written in NuGet NWebSec supports only .NET Standard 1.6 what is mean that it doesn't supports .NET Core yet

**Comment by klings** [comment]
That package is for ASP.NET 4, use the aspnetcore ones instead.
>

**Comment by AshleyPoole** [comment]
Can this be closed now?

**Comment by programmersommer** [comment]
Sure. Clear answer was recieved
