### ISSUE TITLE
Adding NWebsec.Mvc to ASP.NET MVC 5 project causes CORS headers to be omitted from responses.

### ISSUE THREAD

**Issue by abdulrehmangill** [NWebsec/NWebsec#121]
I added the dependency to use the XFrameOptions Attribute.
Before adding the dependencies, all the relevant CORS headers were being sent with each response.

The issue came up when the following dependencies were added.
&lt;package id="NWebsec" version="4.3.0" targetFramework="net462" /&gt;
Add a comment to this line
&lt;package id="NWebsec.Core" version="1.6.0" targetFramework="net462" /&gt;
&lt;package id="NWebsec.Mvc" version="4.3.0" targetFramework="net462" /&gt;

The following dependency already existed in the project.
&lt;package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net45" /&gt;
&lt;package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net45" /&gt;

In the Web API config, the following code already existed
          `config.EnableCors();`  

The above two are the only two pre-requisites to send along CORS headers i.e. enable them. I'm surprised that this issue came up since NWebsec doesn't help you with CORS.

**Comment by papyr** [comment]
same here

**Comment by klings** [comment]
That's weird, I can't see how NWebsec would interfere with CORS. Have you enabled security headers in web.config or through MVC attributes?
