### ISSUE TITLE
Child-src being deprecated => how to declare worker-src ?

### ISSUE THREAD

**Issue by lgmorand** [NWebsec/NWebsec#122]
Hi André,

lovely nugget, used it for months, we love it. In some browsers, we have some warning telling that child-src is becoming deprecated and has to be replaced by frame-src and worker-src

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src#Browser_compatibility

If I found FrameSources(), I don't find anything about worker sources. Did I miss something

thx

**Comment by klings** [comment]
Hi @lgmorand, thanks for the kind feedback. No, you're not missing something. I'm in the process of merging the ASP.NET Core branch and the classic NWebsec branch. Once that's settled, I'll add it in the next release after that.

**Comment by klings** [comment]
Released

**Comment by lgmorand** [comment]
Thanks a lot @klings. I'm a gonna give a try with the new version :)
