### ISSUE TITLE
Support report on X-Xss-Protection

### ISSUE THREAD

**Issue by credfeto** [NWebsec/NWebsec#129]
Can you add the ability to add the report url to the X-Xss-Protection code e.g:

X-Xss-Protection: 1; mode=block; report=https://{url}

See:

https://scotthelme.co.uk/introducing-xss-reporting-to-report-uri/

Thanks

**Comment by troyhunt** [comment]
Just adding my support for this request, would love to see it make it into NWebSec!

**Comment by klings** [comment]
As with most problems, if you wait long enough they go away. :)

The XSS Auditor has been removed from Chrome now, so I'll just leave the `X-Xss-Protection` implementation as is for now for the sake of other browsers.

https://www.chromium.org/developers/design-documents/xss-auditor
