### ISSUE TITLE
Expired SSL Cert on www.nwebsec.com

### ISSUE THREAD

**Issue by robbihun** [NWebsec/NWebsec#140]
Just FYI, not sure if this project is still maintained, but it looks like the SSL cert expired in Feb of this year for nwebsec.com

**Comment by joeaudette** [comment]
I'm seeing this as well, it is May 5, 2019 and the cert expired February 27, 2019. Isn't anyone paying attention to the website?

**Comment by klings** [comment]
Thanks for the ping, yes I had missed the warnings about the cert expiring. It's now behind a "managed" solution so someone else will be paying attention to this next time.
