### ISSUE TITLE
CustomSources ms-appx-web: causes exception

### ISSUE THREAD

**Issue by prainho** [NWebsec/NWebsec#143]
With MS Edge I'm getting a CSP error where the blocked URI is BlockedUri="ms-appx-web://"

I've try add ms-appx-web: to the custom sources but i'm getting an exception.

From what I've seen the problem seems to be in this file:

https://github.com/NWebsec/NWebsec/blob/12fc3425bf724869aeb5e8094dbb211c3b0e65f7/src/NWebsec.Core.Shared/HttpHeaders/Csp/CspUriSource.cs

In the regex used to validate the custom source.

Is it possible to have a fix and build on this or an alternative solution?

**Comment by Sora2455** [comment]
You're probably safe to ignore that extension altogether - that looks like a URL scheme that Edge loads extension resources from. You might break someone's extension on your website, but not your site.

I'd lodge an Edge bug personally. Browsers are supposed to ignore extensions when evaluating CSP. (Bookmarklets too, but none of them do that at the time of writing).

**Comment by klings** [comment]
Assuming this was an Edge artifact. Feel free to reopen the issue if we need to investigate this more.
