### ISSUE TITLE
nonce attribute in CSP header

### ISSUE THREAD

**Issue by anawale** [NWebsec/NWebsec#146]
Issue with the getting nonce attribute in CSP header
Application is in .Net Framework 3.5
NWebSec version is 4.0
Added below Configuration 
```
 <nwebsec>
    <httpHeaderSecurityModule>
    <securityHttpHeaders>
	  <content-Security-Policy enabled="true">
          	<default-src self="true"/>
	          <script-src self="true" unsafeInline= "true">
	            <add source="*.abc.com" />
        	  </script-src>
	 </content-Security-Policy>
   </securityHttpHeaders>
</httpHeaderSecurityModule>
 </nwebsec>
```
The above configuration generates below header
Content-Security-Policy: default-src ‘self’; script-src ‘self’ 'unsafe-inline' *.abc.com

But I believe,  the above header is missing 'nonce' tag it must be something  like 
Content-Security-Policy: default-src ‘self’; script-src ‘self’ 'unsafe-inline' 'nonce-abc123***' *.abc.com

Can someone please let me know , why I am not getting this 'nonce' tag in header.

**Comment by klings** [comment]
Nonces are set through the HtmlHelper, check the docs: https://docs.nwebsec.com/en/aspnet4/nwebsec/Configuring-csp.html#script-and-style-nonces-through-htmlhelpers

The nonce generated by the HtmlHelper will be included in the CSP header.
