### ISSUE TITLE
<script nws-csp-add-nonce="true"> not working ASP.NET Core 2.1

### ISSUE THREAD

**Issue by alcastronava** [NWebsec/NWebsec#148]
Hi, thanks for this usefull tool

I'm trying this and I successfull add the headers to my ASP.NET CORE 2.1 MVC web app.
But I have a problem trying using the nws-csp-add-nonce="true" for my inline scripts.
I already installed the 3 packages
NWebsec.AspNetCore.Middleware
NWebsec.AspNetCore.Mvc
NWebsec.AspNetCore.Mvc.TagHelpers

This is part of my Startup.cs
```
            app.UseXContentTypeOptions();
            // Referrer-Policy header.
            app.UseReferrerPolicy(opts => opts.NoReferrer());
            ////End Ver documentacion 

            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseSession();
            app.UseAuthentication();
            app.UseStatusCodePagesWithReExecute("/Home/Error", "?statusCode={0}"); 

            // X-Xss-Protection header
            app.UseXXssProtection(options => options.EnabledWithBlockMode());
            // X-Frame-Options header
            app.UseXfo(options => options.Deny());
            // Content-Security-Policy header
            app.UseCsp(opts => opts
                .BlockAllMixedContent()
                .StyleSources(s => s.Self())
                .StyleSources(s => s.UnsafeInline())
                .FontSources(s => s.Self())
                .FormActions(s => s.Self())
                .FrameAncestors(s => s.Self())
                .ScriptSources(s => s.Self())
                //.ScriptSources(s => s.UnsafeInline()) 
            );
```
In fact, I added succesfull the 
`<meta name="referrer" nws-referrerpolicy="NoReferrer" />`
but in my views the nonce dosen't work
I try 
`  <script nws-csp-add-nonce="true">`
But later in my web app from google chrome the tag still remains like 
`  <script nws-csp-add-nonce="true">`
It dosen't change to something like 
`<script nonce="buoc1h8zWh0qITh/RHq1">`

What's wrong?
Please help and thank you very much!

See this image
![NWebSec Issue](https://user-images.githubusercontent.com/25377515/61131131-6050ed00-a486-11e9-9b7d-365b92bee8d8.png)

**Comment by crittag** [comment]
I have this working in Core 2.2 - have you included a @using NWebsec in your view/page or _ViewIports.cshtml?

**Comment by klings** [comment]
Yes, check that you have the correct imports: https://docs.nwebsec.com/en/latest/nwebsec/NWebsec.AspNetCore.Mvc.TagHelpers.html

**Comment by LachlannRattray** [comment]
Hey folks for anyone coming across this I found that dev tools in FF shows the value as empty but if you look directly at the source you will see the nonce value.
