### ISSUE TITLE
How to configure an unsafe-eval using the OWIN fluent configuration?

### ISSUE THREAD

**Issue by bounav** [NWebsec/NWebsec#149]
I just noticed that google maps loads a small inline SVG element (it's the shape of an "X").

This generates loads of CSP errors on our application:

```
Content Security Policy: The page’s settings observed the loading of a resource at data:image/svg+xml,%3Csvg%20xmlns%3D%22h… (“img-src”). A CSP report is being sent.
```

Our OWIN is as follow:

```csharp
app.UseCspReportOnly(o => o.DefaultSources(s => s.None())
    .ConnectSources(s => s.Self()
    // ...
    .ReportUris(r => r.Uris("https://xxx.report-uri.io/r/default/csp/reportOnly")));
```

I tried adding a new line to configure object sources but without success:

```csharp
.ObjectSources(s => s.Self().CustomSources("data:*"))
```

The line above adds this to the CSP header: `object-src 'self' data:*` which doesn't help.

Is there a way to configure `unsafe-eval` fluently?

**Comment by Sora2455** [comment]
Rather than `data:*`, you want just `data:`.

**Comment by klings** [comment]
Also, it seems to violate the img-src directive, so you’ll need to add “data:” there.

**Comment by bounav** [comment]
Of course! I was looking the wrong place. Thanks so much for the quick answer.

I changed my image source config from:

```csharp
.ImageSources(s => s.Self().CustomSources("*"))
```

to:

```csharp
.ImageSources(s => s.Self().CustomSources("*", "data:"))
```

and it works ;).
