### ISSUE TITLE
ASP.NET Core 3 support

### ISSUE THREAD

**Issue by DOMZE** [NWebsec/NWebsec#150]
Is there plan to support ASP.NET Core 3 for this library? I haven't seen any news or incentices so I am asking :-)

**Comment by vladimir-kazakov** [comment]
I upgraded from ASP.NET Core 2.2 to 3.0, and noticed that CSP nonces on the script tags are not working anymore.

**Comment by MovGP0** [comment]
I have multiple ASP.NET Core 3.0 projects and would like to use NWebsec.

**Comment by bencgreen** [comment]
> I upgraded from ASP.NET Core 2.2 to 3.0, and noticed that CSP nonces on the script tags are not working anymore.

I don't know if there are any changes to TagHelper handling in ASP.NET Core 3 but this worked for me:

All you need to do is create a TagHelper class in your own project, and copy / paste the code from CspNonceTagHelper.cs (NWebsec.AspNetCore.Mvc.TagHelpers).

Then add this to Views\_ViewImports.cshtml

`@addTagHelper *, your_project_root_namespace

I did that, rebuilt my project, and all works fine.  I don't know why, I can't figure it out - maybe there's a bug (or a breaking change) in the way ASP.NET Core 3 imports TagHelpers from third-party libraries?  Can't find anything online yet but will keep digging.  

At least it's working again!

**Comment by vladimir-kazakov** [comment]
Pretty bad, but interesting workaround.

Anyway, this project (NWebsec) seems to be dead. To solve my problems, I removed the dependency on it. That's exactly what I recommend to others. It's not acceptable that the library that deals with security has such a poor support.

P.S. I mostly needed this library because of CSP nonces. I knew that it's a bad idea to mix styles and scripts with the markup, but at that time I didn't want to bother with moving everything out to separate files. Eventually, I did it. It didn't take much time, refactoring was quite simple, and as a result I've got an ability to minify and compress `.css` and `.js` files, and to verify their integrity using subresource integrity (SRI). So, the end result is more maintainable, secure, and performant. And, of course, minus one dependency, which is always a good thing.

**Comment by bencgreen** [comment]
Yeah I agree, it's all well and good using other people's work to save time - but then when things are no longer maintained it causes more issues.

I use this for nonces, but also for adding HSTS settings etc more easily.  I use the nonces not only for inline script, but also for script files, and then have some extremely strict security settings.

**Comment by Choc13** [comment]
I have another Razor library containing some tag helpers. It seems that Tag Helper authors need to add the following to their csproj as referenced in the ASP.NET Core 3.0 migration [docs](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#razor-class-library):

```
<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
```

I'm not 100% sure that this is the only change that needs to be made to get this working, but it seems like it's definitely a necessity.

**Comment by Choc13** [comment]
Actually I also had to update the Razor dependency in the library too. It didn't work until I had the following:

```
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.2.0" />
```

It seems 2.2.0 is the minimum requirement for that package.

**Comment by Choc13** [comment]
There's also some more useful information in this [blog post](https://andrewlock.net/converting-a-netstandard-2-library-to-netcore-3/) which details how to migrate libraries to support ASP.NET Core 3.0.

**Comment by klings** [comment]
I've pushed RC packages with support for 3.1, you can try out those if you want. I'll push the release packages in a day or two, just need to do a bit of verification on the "old" NWebsec too.

**Comment by garyapps** [comment]
I just tried this in an Asp core 3.1 app. It does not work... the nonces do not appear. I am using the latest version of nwebsec which I obtained using NuGet (v3.0.0).

Are some additional changes required? The nonces used to appear prior to updating the asp core app from 2.1 to 3.1. The ViewImports.cshtml file already has the two requred addTagHelper statements mentioned [here](https://docs.nwebsec.com/en/latest/nwebsec/NWebsec.AspNetCore.Mvc.TagHelpers.html#csp-nonces)

As far as I can tell the change you rolled out did not fix the problem.

**Comment by garyapps** [comment]
Ignore my previous post - I realized I only had the NuGet package for NWebsec.AspNetCore.Middleware was missing the NuGet package for NWebsec.AspNetCore.Mvc.TagHelpers (therefore the middleware was working and setting up CSP, but the tag helpers that provide the nonce were not working).

**Comment by klings** [comment]
That sounds like expected behaviour, thanks for the update! :)
