### ISSUE TITLE
Non-MVC WebForms ASPX Support

### ISSUE THREAD

**Issue by cgountanis** [NWebsec/NWebsec#158]
I assume the NUGET and Web.Config are basically the same but is there any documentation on usage with WebForms? Still supporting some older applications for a couple years.

**Comment by klings** [comment]
Yes there is: https://docs.nwebsec.com/en/aspnet4/

Go with the `NWebsec` package and configure it through web.config.

**Comment by cgountanis** [comment]
That does not help with nonce all that does is configure the headers which you can do manually in IIS. Right?

**Comment by klings** [comment]
That's right, no nonces for WebForms.
