### ISSUE TITLE
CSP with Bootstrap 4 DefaultSources/ImageSources

### ISSUE THREAD

**Issue by cgountanis** [NWebsec/NWebsec#159]
Having issues with Bootstrap 4 and setting `.DefaultSources(s => s.Self())` &` .ImageSources(s => s.Self())`, seems there are many issues with base64 images and inline styles, etc..., is there a way to allow all that local only?

**Comment by cgountanis** [comment]
e.g.

The page’s settings blocked the loading of a resource at data:image/png;base64,iVBORw0KGgoAAAANSU… (“img-src”).

The page’s settings blocked the loading of a resource at inline (“default-src”)

**Comment by klings** [comment]
You can allow the resource to load by adding `data:` to the `img-src` directive, but see the discussion in #74 before you do that.
