### ISSUE TITLE
Default/Script Self() Bug?

### ISSUE THREAD

**Issue by cgountanis** [NWebsec/NWebsec#162]
Might be a bug not sure. If you set the Default Source to Self() then set the Script Source to Self() and add Custom Source it ignores the NONCE settings. As a work-around I was able to just use Custom Source under Script but I would think picking up the Default or setting it directly to Self should work, just a bit confusing.

Work Around (NONCE WORKS)
.DefaultSources(s => s.Self())
.ScriptSources(s => s.CustomSources(scriptCustomSources))

What You Should Be Able To Do?  (NONCE DOES NOT WORK)
.DefaultSources(s => s.None())
.ScriptSources(s => s.Self().CustomSources(scriptCustomSources)) <- You would think you could use None() here but this gives you a none error in console, ignored. Then if you use None you can not use CustomSources, urg...

It's just confusing, I know you can not have None with a CustomSources but if you want to use NONCE you kinda have to. Strange it works with Default .Self() then by setting the Script CustomSources it seems to fool it into Script None mode with NONCE. Just confusing...

**Comment by cgountanis** [comment]
I switched to a more start with NONE approach and it makes a bit more sense like this and the NONCE does work properly.

```
// Default settings.
.DefaultSources(s => s.None())
.ReportUris(r => r.Uris("XXX"))

// Exceptions.
.FontSources(s => s.Self())
.FrameSources(s => s.CustomSources(frameCustomSources))
.ImageSources(s => s.Self().CustomSources("data:"))
.ScriptSources(s => s.CustomSources(scriptCustomSources))
.StyleSources(s => s.Self().UnsafeInline())

// Misc
.BlockAllMixedContent());
```

**Comment by klings** [comment]
Glad you got it working. I assume that the "nonce does not work" means that it was present in the header but your CSP policy did not work as you expected? But NWebsec did?

Feel free to reopen the issue if NWebsec did not work as expected. If possible include your config and the resulting header.
