### ISSUE TITLE
Bug In SchemeOnlyRegex String

### ISSUE THREAD

**Issue by lanfear** [NWebsec/NWebsec#163]
I feel like there is a bug here.  We have a couple custom schemes we must define in our CSP to support our desktop apps.

AFAIK, custom our custom schemes are valid defined as something like `myco-mycoapp:`.

https://github.com/NWebsec/NWebsec/blob/b8cc06444e8bd7fd4236de3b157504056b591ac2/src/NWebsec.Core.Shared/HttpHeaders/Csp/CspUriSource.cs#L14

But the code throws a `InvalidCspSourceException: Malformed CSP source:` exception.

I believe there is just a bug in the custom regex definition where

`SchemeOnlyRegex = "^[a-zA-Z]*[a-zA-Z0-9" + Regex.Escape("+.-") + "]:$";`

Should read

`SchemeOnlyRegex = "^[a-zA-Z][a-zA-Z0-9" + Regex.Escape("+.-") + "]*:$";`

Meaning it must start with an 'alpha', then must contain any number of 'alphanumeric' plus the 3 allowed special chars.

As it reads now it must start with any number of 'alpha' characters and then end with a single 'alphanumeric' + allowed special chars.

Thanks for considering, if i get time I will open up a PR.

**Comment by klings** [comment]
I´ll have a look.

**Comment by klings** [comment]
I checked the standard, you're right. https://tools.ietf.org/html/rfc3986#section-3.1

I'll get that fixed in the next release.
