### ISSUE TITLE
Ability to add nonce without TagHelper?

### ISSUE THREAD

**Issue by dotnetshadow** [NWebsec/NWebsec#167]
Hi there,

Firstly a great library. I was wondering is there a way to add nonce to scripts that get injected in the page, i.e that don't use a taghelper? 

```
<script nws-csp-add-nonce="true">alert('yes');</script>
<script>alert('blocked');</script> <--- imagine coming from a 3rd party script
```

The second script won't get executed because it doesn't have nonce on it. 
Is there a way for those scripts to get the injected nonce?

**Comment by Sora2455** [comment]
If the third-party script is static, you could add a hash.

If the script isn't static, you are trusting everything on your website to the security + trustworthiness of the third party, now and into the future unto eternity, and frankly I would look into _finding_ a static alternative.

**Comment by dotnetshadow** [comment]
Thanks for the prompt response. That's a good point you raised about trusting the third party.

I had a nuget package that would inject a script, i.e.  something like Application Insights so I was just curious about how to handle that situation since I don't have control over the script generation. 

My original thinking was I would need a middleware to rewrite <script> tags or something

**Comment by dotnetshadow** [comment]
> If the third-party script is static, you could add a hash.

So I would add the hash through **CustomSources()**?

**Comment by Sora2455** [comment]
I believe so, yes. (I'm not actually the owner of NWebsec).

**Comment by dotnetshadow** [comment]
Cheers thanks
