### ISSUE TITLE
CSP Middleware multiple custom sources

### ISSUE THREAD

**Issue by muni20** [NWebsec/NWebsec#169]
how do you add multiple custom sources in Middleware.

**.ScriptSources(s => s.Self().CustomSources("scripts.nwebsec.com ajax.googleapis.com"))**

or do i have to Configuring CSP through MVC attributes 

**[CspScriptSrc(CustomSources = "scripts.nwebsec.com ajax.googleapis.com")]**

**Comment by klings** [comment]
Pass them in as an array?

"scripts.nwebsec.com", "ajax.googleapis.com"


HTH

**Comment by muni20** [comment]
i tried ("scripts.nwebsec.com"+ "ajax.googleapis.com")
so dumb of me 
"scripts.nwebsec.com", "ajax.googleapis.com" worked 

**Thanks**
