### ISSUE TITLE
Non-MVC WebForms ASPX .Net 4.6.1 - Basic configuration not working.

### ISSUE THREAD

**Issue by bxsingh1** [NWebsec/NWebsec#174]
I need to support an older website running on .Net 4.6.1. To test the nwebsec support for asp.net webforms, I followed these steps: 
1. Created a brand new Asp.net webforms project in VS 2017 using .net 4.6.1.  Tested it as working.
2. Added a NuGet package as specified here<https://www.nuget.org/packages/NWebsec/>: Install-Package NWebsec -Version 6.0.0
3. Changed the Web.config [Web_config.txt](https://github.com/NWebsec/NWebsec/files/5771329/Web_config.txt) file to include the following:

```
  <nwebsec>
    <httpHeaderSecurityModule xmlns="http://nwebsec.com/HttpHeaderSecurityModuleConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NWebsecConfig/HttpHeaderSecurityModuleConfig.xsd">
      <securityHttpHeaders>
        <content-Security-Policy enabled="true">
          <default-src self="true"/>
          <script-src self="true" enabled="true">
            <add source="maxcdn.bootstrapcdn.com" />
            <add source="code.jquery.com" />
            <add source="ajax.googleapis.com" />
            <!--<add source ="localhost:60252"/>-->
          </script-src>
          <style-src self="true" />
          <report-uri enableBuiltinHandler="true"/>
        </content-Security-Policy>
      </securityHttpHeaders>
    </httpHeaderSecurityModule>
  </nwebsec>
```

4. Saved and Ran the project.
5. I got the following errors in Google Chrome Console:
```
`modernizr-2.8.3.js:134 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-CwE3Bg0VYQOIdNAkbB/Btdkhul49qZuwgNCMPgNY5zw='), or a nonce ('nonce-...') is required to enable inline execution.

localhost/:20 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' maxcdn.bootstrapcdn.com code.jquery.com ajax.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-uYoAmCrBFM4tx/Ww+6eFuIJxuwZ3YFRT7fWUTlgnPuE='), or a nonce ('nonce-...') is required to enable inline execution.

localhost/:39 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' maxcdn.bootstrapcdn.com code.jquery.com ajax.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-2vr5KMButMK7a+bOf/ned/cPnF2yNooMulXA8E65wGw='), or a nonce ('nonce-...') is required to enable inline execution.

localhost/:52 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' maxcdn.bootstrapcdn.com code.jquery.com ajax.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-AJipRK0+ga273yKzZZX3BqTHwvwc1v3R9erdu31Wh6I='), or a nonce ('nonce-...') is required to enable inline execution.`
```

 Any help/pointers/support is appreciated.

**Comment by Sora2455** [comment]
At a guess, I'd say that Modernizr is trying to add inline styles and scripts as part of its testing suite. If you don't actually use Modernizr, I'd recomend removing it and trying again - or at least going to the Modernizr website and downloading a version of the script that only has the tests you actually want.

**Comment by bxsingh1** [comment]
After removing Modernizr, I still have the following three errors:
![image](https://user-images.githubusercontent.com/77014578/103688999-b1994a00-4f60-11eb-9630-df04533fc863.png)
I would like to stress that the script shown in the image is not mine, it is being inserted by the ASP.net webforms framework. Also this is a plain vanilla Asp.net web application. The actual source code of the page shown above(with errors) is as follows:

```
<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="DummyWebApp4_6_1.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>Your application description page.</h3>
    <p>Use this area to provide additional information.</p>
</asp:Content>

```

**Comment by Sora2455** [comment]
Oh, you're using ASP.NET Web Forms. Sorry, I missed that.

Anyway, you're not going to be able to use a script-src CSP directive with web forms. As you've discovered, the ASP.NET Framework inserts scripts on the page dynamically that are required for the postback functionality to work. You can't whitelist them with a hash either - the script block's contents are dynamic, and inline event handlers are added to any form control with auto-postback set on.

**Comment by bxsingh1** [comment]
@Sora2455 Thank you so much for responding. 
Is there an older version of NWebsec that I might be able to use with Webforms if it lets me use the script-src CSP directive. 
Also would you happen to know of any alternative that I might use to enforce whitelisting of scripts via CSP in a Asp.Net Web Forms application... Thanks in advance.

**Comment by Sora2455** [comment]
It's not a problem with NWebsec, it' a problem with Web Forms. Becuase it needs inline event handlers to work correctly - and becuase those inline event handlers are dynamic, i.e. can't be whitelisted with a hash - you have to add the 'unsafe-inline' (with the quotation marks) directive to your script-src directive to avoid blocking web forms with your CSP. (Sorry, I was misleading before when I said it couldn't be done.)

However, this removes 90% of the point of using a script-src directive, as now all inline scripts on your page will run, both yours and any XSS-injected ones. The only script injection attack this will block is if someone tries to inject an external script tag.

**Comment by bxsingh1** [comment]
@Sora2455 Thank you so much for the feedback.
