### ISSUE TITLE
Unrecognized attribute 'noNamespaceSchemaLocation'. Note that attribute names are case-sensitive.

### ISSUE THREAD

**Issue by klings** [NWebsec/NWebsec#43]
Issue added from old project site. http://nwebsec.codeplex.com/workitem/43

**Comment by kl00t** [comment]
What was the solution for this?

**Comment by klings** [comment]
It needed special handling in code. Are you getting this error when using
NWebsec?

**Comment by i4rilu** [comment]
It is still reproducible in v5.1.1 when OPTIONS verb is being denied on IIS web server.

**Comment by aiskhylos** [comment]
Was there a solution for this? Any updates on this be greatly appreciated.

**Comment by TerryDieckmann** [comment]
Having the same issue...

**Comment by marisha7** [comment]
any updates on this issue? I am getting same error for upgrade from 4.5 to 4.8
