### ISSUE TITLE
HPKP support

### ISSUE THREAD

**Issue by klings** [NWebsec/NWebsec#49]
Add support for Public Key Pinning. HPKP is currently supported in Chrome and Firefox.

**Comment by RehanSaeed** [comment]
I've learned so much using NWebSec. Added to my <a href="https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/TODO.md">TODO list</a>.

**Comment by klings** [comment]
Good to hear. And I've learnt a lot from building it!

**Comment by RehanSaeed** [comment]
I noticed you've added the report URL. Any plans to provide similar support to CSP which has the NWebsecHttpHeaderSecurityModule_CspViolationReported method you can add to Global.asax.cs?

Looking ahead to ASP.NET 5 and MVC 6, you could probably provide a delegate where developers can do whatever they want. CSP could be done similarly. Something like this:

```
app.UseHpkp(options => options
                .Sha256Pins(
                    "Base64 encoded SHA-256 hash of your first certificate e.g. cUPcTAZWKaASuYWhhneDttWpY3oBAkE3h2+soZS7sWs=",
                    "Base64 encoded SHA-256 hash of your second backup certificate e.g. M8HztCzM3elUxkcjR2S5P4hhyBNf6lHkmjAHKhpGPWE=")
                .MaxAge(days: 30)
                .IncludeSubdomains()
                .ReportUri(
                    report =>
                    {
                        // Log report
                    }));
```

**Comment by klings** [comment]
Well, the reporting does not quite work the same for HPKP. For CSP 1.0, the
report-uri has to be a relative URI, which in many cases means the very
same application. Therefore, I added the report handling since that could
be enabled by a single attribute in config and I could also easily pick
them up server side and raise an event.

For PKP it doesn't make sense to point the report-uri to the same domain.
The reason is, the UA must validate pins also for the report-uri. In
effect, if you have a pin validation failure on https://www.example.com,
you would not be able to report it to https://www.example.com/report . The
alternative would be to report them in cleartext (http), but that is not
something I'd want to encourage.

Since you'll have to report it elsewhere, a similar trick to that of the
CSP reporting wasn't a natural fit.

You might also notice that there's no NWebsec CSP report handling
middleware. I might add report handling middleware, but I might also
provide an example controller, but provide the report class itself for easy
model binding. A middleware would of course be along the lines of what you
propose. I'll have to give it some thought when I start working on the MVC
6 stuff.

**Comment by RehanSaeed** [comment]
I see. I was hoping to add reporting to Elmah. I think most devs will not go as far as setting up a new site and TLS just to log these reports. What would be the implications of reporting over basic HTTP? Perhaps I could add that as a poor mans option?

I think an example controller would be a good fit for MVC 6 reporting. It would be a good excuse to add an API controller maybe.

**Comment by klings** [comment]
Well, unless you've messed up the certs for the site, a pinning validation
failure would mean that there's an active middleperson attack on the
connection. If there's an active attack the reports could easily be
blocked, or if sent in cleartext they could be altered to disguise the
attack.

The best recommendation would probably be to have a report site running
over TLS (with pinning) on a totally different network, to increase the
chance of receiving correct reports.

There are third party sites such as https://report-uri.io/ that offer this
as a service, but application owners should always carefully consider with
whom they're comfortable sharing their security violations with.

**Comment by RehanSaeed** [comment]
Thanks for the link. It looks like a good starting point. Will do some reading later.
