### ISSUE TITLE
Minor - Better Exception Message

### ISSUE THREAD

**Issue by RehanSaeed** [NWebsec/NWebsec#52]
Very low priority. I got the following error:

<pre>Exception message: No sources configured for attribute. Remove attribute, or set "Enabled=false"
at NWebsec.Mvc.HttpHeaders.Csp.Internals.CspDirectiveAttributeBase.ValidateParams()</pre>

It would be nice to get an indication of which attribute threw this exception as I would imagine this would be a fairly common one to get because someone forgot to add a Self = true.

**Comment by klings** [comment]
Hmm. The MVC configuration is now validated on initialization, not on first run. I'll have a look, I see that this makes it harder to find out what's wrong. Thanks for reporting this.
