### ISSUE TITLE
plugin-types directive

### ISSUE THREAD

**Issue by RehanSaeed** [NWebsec/NWebsec#53]
I'm just going through adding the CSP 2.0 directives to <a href="https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate">ASP.NET MVC Boilerplate</a> and noticed that the <a href="http://www.w3.org/TR/CSP2/#directive-plugin-types">plugin-types</a> directive does not seem to be implemented.

**Comment by klings** [comment]
Ah, yes. I had to split CSP 2 into several pieces, and plugin-types needs a bit of thought. It will hopefully be included in the next release.
