### ISSUE TITLE
Using Content-Security-Policy for Evil

### ISSUE THREAD

**Issue by RehanSaeed** [NWebsec/NWebsec#56]
I came accross <a href="http://homakov.blogspot.co.uk/2014/01/using-content-security-policy-for-evil.html">this</a> blog post in which CSP is used to figure things out about the user. It looks interesting, not sure what you can do to mitigate this.

I'm 3/4 of the way through my CSP write up. It's going to be a long blog post.

**Comment by klings** [comment]
Yes, you'll see that it's referred in the CSP level 2 specification. They did a few changes to the spec to help hamper these types of attacks. CSP is a complex beast, so the short blog posts out there hardly scratch the surface of it. :)
