### ISSUE TITLE
Server header is exposing important information (Solution Suggestion)

### ISSUE THREAD

**Issue by ramyhhh** [NWebsec/NWebsec#57]
Hello ... Sorry I couldn't check everything about it in details, but I knew that the Server header couldn't be removed since the last upgrade of NWebsec.
I suggest changing the value of the server header as a kind of obfuscation instead of totally removing it. I have tried changing the Server header into something like Apatche and it worked and IIS didn't realize the change.

**Comment by klings** [comment]
Well, opinions vary on whether the server header really exposes valuable information. See the last couple of paragraphs in the docs for [Suppressing version headers](https://github.com/NWebsec/NWebsec/wiki/Suppressing-version-headers).

I suggest we leave this issue hanging, and I'll have another look at it when I'm done with the work to support ASP.NET vnext.

**Comment by klings** [comment]
Closing this, this won't change for the ASP.NET 4 NWebsec.
