### ISSUE TITLE
Could not load file or assembly NWebsec.Annotations

### ISSUE THREAD

**Issue by ChrisHimsworth** [NWebsec/NWebsec#58]
I have just updated to NWebsec.Mvc v4.0.0 (and related dependencies) and I now getting the following error message:
Could not load file or assembly 'NWebsec.Annotations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3613da5f958908a1' or one of its dependencies. The system cannot find the file specified.

Calling assembly : NWebsec.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=3613da5f958908a1.

The NWebsec.Annotations.dll didn't seem to be included in the NWebsec.Core Nuget package.

**Comment by klings** [comment]
That's weird, the annotations assembly contains only internal classes, referenced by the other NWebsec assemblies, and is there for ReSharper only. This is the first time I've heard about this issue.

Have you done anything out of the ordinary? Have you e.g. subclassed something?

**Comment by ChrisHimsworth** [comment]
I am using PiranhaCMS (https://github.com/PiranhaCMS/Piranha) on my site, which uses MEF and scans assemblies, which I think may be raising the error.

**Comment by klings** [comment]
Ah, that could explain it. I'll see if I can get rid of the attributes in
the next release build.
