### ISSUE TITLE
'sandbox' CSP directive ommitted when no allow-* are specified

### ISSUE THREAD

**Issue by vossad01** [NWebsec/NWebsec#61]
NWebsec does not enable CSP's Sandbox unless at least one `Allow*` method is called on the `IFluentCspSandboxDirective`

```
owin.UseCsp(
   opt => opt.DefaultSources( src => src.None() ).Sandbox( c => { } ) );
```

Actual Header:

> content-security-policy default-src 'none'

Expected Header:
> content-security-policy	default-src 'none'; sandbox

**Comment by klings** [comment]
Ugh, that sounds like an undisputable bug. I'll take a look. Thanks for reporting this.
