### ISSUE TITLE
Referrer policy

### ISSUE THREAD

**Issue by klings** [NWebsec/NWebsec#62]
Standard: http://www.w3.org/TR/referrer-policy/

Browsers are starting to support Referrer policy through meta tags. Firefox seem to support the new (and preferred) keywords, while Chrome seems to only support the old ones.

Support is also underway in IE. http://dev.modern.ie/platform/status/metareferrer

**Comment by RehanSaeed** [comment]
This is cool, I can remove my HTML helper from Boilerplate. I was going to implement a ASP.NET 5 tag helper for this. I won't if you have plans to do this.

**Comment by klings** [comment]
Yes, this has been hanging around for a while, but the HtmlHelper will be included in the next relase.
