### ISSUE TITLE
Intermittent IIS App pool fails.

### ISSUE THREAD

**Issue by Isbars** [NWebsec/NWebsec#64]
This is the only message in the IIS logs and windows error logs 

The full redacted message is: 
 
Event code: 3008
Event message: A configuration error has occurred.
Event time: 09/07/2015 14:23:11
Event time (UTC): 09/07/2015 13:23:11
Event ID: d82a76716245475d99a717e86f15aa8c
Event sequence: 30498
Event occurrence: 750
Event detail code: 0
 
Application information:
    Application domain: /LM/W3SVC/2/ROOT-1-130808223125849154
    Trust level: Full
    Application Virtual Path: /
    Application Path: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Machine name: xxxxxxxxxxxxxxx
 
Process information:
    Process ID: 1480
    Process name: w3wp.exe
    Account name: xxxxxxxxxxxxxxxxx
 
Exception information:
    Exception type: ConfigurationErrorsException
    Exception message: Required attribute 'x-Robots-Tag' not found. (E:\Websites\xxxxxxxxxxxx\xxxxxxx\web.config line 235)
 
Request information:
    Request URL: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Request path: xxxxxxxxxxxxxxxxxxxx
    User host address: xxx.xx.xx.xx
    User: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Is authenticated: True
    Authentication Type: xx
    Thread account name: xx
 
Thread information:
    Thread ID: 6
    Thread account name: xx
    Is impersonating: False
    Stack trace:    at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, 
 
SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object 
 
parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord 
 
sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& 
 
resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, 
 
Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& 
 
resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Web.HttpContext.GetSection(String sectionName)
   at System.Web.Configuration.WebConfigurationManager.GetSection(String sectionName)
   at NWebsec.HttpHeaders.HttpHeaderHelper.get_BaseConfig()
   at NWebsec.HttpHeaders.HttpHeaderHelper.GetSuppressVersionHeadersWithOverride(HttpContextBase context)
   at NWebsec.HttpHeaders.HttpHeaderHelper.SetHeaders(HttpContextBase context)
   at NWebsec.Modules.HttpHeaderSecurityModule.AppPreSendRequestHeaders(Object sender, EventArgs ea)
   at 
 
System.Web.HttpApplication.SendResponseExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by klings** [comment]
This exception tells me that this is NWebsec 2.x, as it's using the PreSendRequestHeaders event. Microsoft deprecated this event a long time ago, and NWebsec was rewritten to no longer use this event. See the NWebsec 3.0 release notes for Microsoft's statement about the issue. This might very well be related. http://nwebsec.codeplex.com/releases/view/114532

Please upgrade NWebsec to the latest version, if the issue surfaces there I'll dig into it.

**Comment by klings** [comment]
As I've had no other similar reports, and you're running a (very) old version of NWebsec, I'll close the issue for now. I strongly urge that you upgrade to the latest version of NWebsec. Should you still experience these issues with the latest version, please reopen this issue.
