### ISSUE TITLE
Upgrade Insecure Requests

### ISSUE THREAD

**Issue by klings** [NWebsec/NWebsec#68]
Standard: http://www.w3.org/TR/upgrade-insecure-requests/

This seems to have decent browser support already, but will need a bit work (and thought).

**Comment by RehanSaeed** [comment]
Is there a way to set this using MVC filters or do we have to use the web.config or OWIN middleware?

**Comment by klings** [comment]
No, this is web.config or middleware only.

**Comment by RehanSaeed** [comment]
I tried adding the middle-ware as well as using MVC filters but this scenario doesn't seem to be supported. Are you planning on adding MVC support or allowing MVC users to use the middle-ware  as well?

**Comment by klings** [comment]
In general, you can specify a base configuration with the middleware and then override with the MVC attributes as needed.

Could you share your CSP config and the resulting header?

**Comment by RehanSaeed** [comment]
Ignore me, I messed up. It seems to work fine using the code below:

```
app.UseCsp(x => x.UpgradeInsecureRequests());
```

**Comment by klings** [comment]
Sure, glad to hear you got it working!
