### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by klings** [NWebsec/NWebsec#69]
Standard: https://w3c.github.io/webappsec/specs/mixedcontent/

Not sure about the browser support.

**Comment by RehanSaeed** [comment]
Apparently [Chrome](https://www.ietf.org/mail-archive/web/websec/current/msg01611.html) and [FireFox](https://bugzilla.mozilla.org/show_bug.cgi?id=838395) both show mixed content warnings even if you use HSTS.

Isn't `Content-Security-Policy: block-all-mixed-content` the same as using HSTS though, don't they both try to achieve the same things, once the above HSTS bugs are fixed?

**Comment by klings** [comment]
Well, they're not exactly the same. `block-all-mixed-content` will prevent the content from loading (same origin or third party), while HSTS will securely load same origin resources, but not do anything about third party resources.

Yes, `upgrade-insecure-requests` is nice, but would give you a network error if content couldn't be loaded over https. So there are probably some cases were you'd want to give a blocking error instead.

**Comment by RehanSaeed** [comment]
I was just thinking about what a sensible default might be. `Content-Security-Policy: block-all-mixed-content` seems a bit militant and I'm going to get developers complaining that their site is not working but `Content-Security-Policy: upgrade-insecure-requests` seems safer masks the real problem and but as you say it may break the site anyway.

Do either of these report CSP errors if they have to block or upgrade a HTTP request? If they don't, it might be better to not use either directive and rely on developers looking at the browser mixed content warnings and fixing the problem themselves.

What do you think?

**Comment by klings** [comment]
Oh, you're thinking of adding this to the NWebsec config in the boilerplate template? In that case `upgrade-insecure-requests` could be a road to disaster. The NWebsec implementation will redirect to https if it's enabled, and the browser supports it. If anyone wants to run the app over http and not https, that would break the app.

The template is used when creating new projects from scratch, right? In that case, `block-all-mixed-content` would be the preferred option. It might be a bit early to add it though, as there's still some discussion going on about the directive, and I'm not sure it's supported by any browsers yet. IIRC it's behind a flag in Chrome, and not implemented in Firefox.

**Comment by RehanSaeed** [comment]
I have added features to my boilerplate project templates now. Some things can be turned on or off (In the next update, **everything** can be turned on or off).

I have a HTTPS Everywhere feature which already turns on, HTTPS port, redirect to HTTPS, HSTS and HPKP. I could just add `upgrade-insecure-requests` or `block-all-mixed-content` to it. Just thinking ahead, once again cool to learn stuff just by looking at the NWebSec issues.

**Comment by klings** [comment]
Released.
