### ISSUE TITLE
Web.config report-uri element isn't correctly configuring the CSP-ReportOnly header.

### ISSUE THREAD

**Issue by necoras** [NWebsec/NWebsec#71]
I have the following in my web.config:

        <content-Security-Policy-Report-Only enabled="true">
          <report-uri enableBuiltinHandler="false">
            <add report-uri="/ReportHandler/ProcessReport" />
          </report-uri>
        </content-Security-Policy-Report-Only>

I expected to see "report-uri /ReportHandler/ProcessReport" added onto the CSP header in my generated pages, but it isn't present. The identical tags in the standard CSP elements:

        <content-Security-Policy enabled="true">
          <report-uri enableBuiltinHandler="false">
            <add report-uri="/ReportHandler/ProcessReport" />
          </report-uri>
        </content-Security-Policy>

do generate the expected header element. 

Additionally, enabling the built in handler in Report Only Mode also fails to correctly add the expected "WebResource.axd?cspReport=true" to the resulting CSP policy.

**Comment by klings** [comment]
Note that NWebsec will not set the header if only the report-uri directive is set, you need to set at least one more directive. Do you get a CSP header in the response at all?

Using e.g

    <content-Security-Policy-Report-Only enabled="true">
      <default-src self="true"/>
       <report-uri enableBuiltinHandler="true">
         <add report-uri="/ReportHandler/ProcessReport" />
       </report-uri>
     </content-Security-Policy-Report-Only>

Gives this header

    Content-Security-Policy-Report-Only: default-src 'self';report-uri /DemoSiteMvc4/WebResource.axd?cspReport=true /ReportHandler/ProcessReport

**Comment by necoras** [comment]
Yes, I do get a CSP header, but I'm defining everything other than the remote-uri property via a global filter. I'm only using the web.config to define remote-uri because it doesn't look like that's supported at the filter level. I'll test if setting an additional directive in the web.config enables the report-uri directive as well.

**Comment by klings** [comment]
Ah, ok, you've probably stumbled over an edge-case. I'll have a look.

You can use the `[CspReportUri]` or `[CspReportUriReportOnly]` attributes to configure the report-uri directive.

**Comment by klings** [comment]
Well, it seems to work as expected here. Could you share which attributes you used in combination with the web.config? Note that the attributes that configure the "report only" header are all named ...ReportOnly. If you combined the CSP attributes with "report only" config, that would explain it.

**Comment by necoras** [comment]
I have filters for the Default, Connect, Font, Frame, Img, Script, and Style sources. 

One thing that might be problematic is that I have filters for both the standard and style attributes for each in order to allow for some alarms on some unsafe directives we must allow due to certain technologies requiring them. Is it possible that your code expects only one or the other but not both?

**Comment by necoras** [comment]
I believe I've found the source of my issue. I didn't have a CspReportOnlyAttribute filter, but rather a CspReportUriReportOnlyAttribute (thank you intellisense/fat fingering). It looks like the CspReportUriReportOnlyAttribute filter overrides the web.config's report-uri element. I'm not sure if that's intentional or not.

After removing the CspReportUriReportOnlyAttribute and replacing it with CspReportOnlyAttribute I'm now seeing the report-uri element as expected. Thanks

**Comment by klings** [comment]
Yes, that's intentional. This lets you alter or override the configuration in web.config (or from middleware) config for controllers and actions. You'll find it mentioned here https://docs.nwebsec.com/en/4.2/nwebsec/NWebsec.Mvc.html

I've just recently moved the docs to docs.nwebsec.com (hosted by readthedocs.org), which enables a much better document structure. I'll have to find some time to restructure the docs, which will make this a bit more discoverable.
