### ISSUE TITLE
error on config

### ISSUE THREAD

**Issue by patagoniahiker** [NWebsec/NWebsec#72]
Hello, following the directions on the doc site, when I paste this inside the
 web.config  <configuration> section I get an error

`<configSections>
<sectionGroup name="nwebsec">
      
      <section name="httpHeaderSecurityModule" type="NWebsec.Modules.Configuration.HttpHeaderSecurityConfigurationSection, NWebsec, Version=4.2.0.0, Culture=neutral, PublicKeyToken=3613da5f958908a1" requirePermission="false" />
    </sectionGroup>
    <nwebsec>
      <httpHeaderSecurityModule xmlns="http://nwebsec.com/HttpHeaderSecurityModuleConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NWebsecConfig/HttpHeaderSecurityModuleConfig.xsd">
        <redirectValidation enabled="true" />
        <securityHttpHeaders>
          <x-Frame-Options policy="Deny"/>
          <x-Content-Type-Options enabled="true" />
        </securityHttpHeaders>
      </httpHeaderSecurityModule>
    </nwebsec>
</configSections>`

**Comment by klings** [comment]
Please provide the error message you get.

**Comment by patagoniahiker** [comment]
Reading your Wiki  :+1: , I pasted the configuration for the MVC, and I have tried various combinations after installing the latest nuget.

1. It says no valid child element/attribute NWEBSEC, 
2. I tried to put it in its own secontiongroup and that did not work either

*. Can you tell me *if this replaces the default section group that gets installed in the web.config?
*. Can you provide a sample of the web.config after installing the nuget pacakge (I dont want to install all of broiler plate just your plugin



 ` <sectionGroup name="nwebsec">
      
      <section name="httpHeaderSecurityModule" type="NWebsec.Modules.Configuration.HttpHeaderSecurityConfigurationSection, NWebsec, Version=4.2.0.0, Culture=neutral, PublicKeyToken=3613da5f958908a1" requirePermission="false" />

      

      

      <nwebsec>
        <httpHeaderSecurityModule xmlns="http://nwebsec.com/HttpHeaderSecurityModuleConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NWebsecConfig/HttpHeaderSecurityModuleConfig.xsd">
          <redirectValidation enabled="true" />
          <securityHttpHeaders>
            <x-Frame-Options policy="Deny"/>
            <x-Content-Type-Options enabled="true" />
          </securityHttpHeaders>
        </httpHeaderSecurityModule>
      </nwebsec>
    </sectionGroup>`



Here is the IIS Express error from client side

`Detailed Error Information:
Module	   IIS Web Core
Notification	   Unknown
Handler	   Not yet determined
Error Code	   0x8007000d
Config Error	   Unrecognized element 'httpHeaderSecurityModule'
Config File	   \\?\D:\Apl\Apl.dmin\web.config

Config Source:
   27:      
   28:         <httpHeaderSecurityModule xmlns="http://nwebsec.com/HttpHeaderSecurityModuleConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NWebsecConfig/HttpHeaderSecurityModuleConfig.xsd">
   29:           <redirectValidation enabled="true" />`

**Comment by klings** [comment]
When you install the NuGet package, it will add everything you need to web.config. It won't remove anything. The changes it makes are documented here: https://docs.nwebsec.com/en/4.2/nwebsec/Configuration.html

You can then configure the headers under the nwebsec/httpHeaderSecurityModule element. In Visual Studio you'll get intellisense support for the configuration section, so you can simply type < to get started.

HTH.

**Comment by patagoniahiker** [comment]
In IIS 8.5 server 2k12 R2 it has Dynamic IP protection for DOS. (I was going to request a feature to incorporate this, I have some sample code from best practices, I wanted to put in your lib, as a filter), The site stops serving randomly, when I enable the Dynamic IP Protection in IIS and, the combinations on which to try is just overwhelming. I would like one good *conservative* sample base version to work off.

I also looked at the section/link, the top section/sample seems very minimal (is this an opt-iin) or opt-out by default? Specifically, the elements and what they represent, and I was sharing earlier, the combinations to use in the application are the issues for me.

*    I am looking for help on a sample of what looks like a good balance between **site accessibility** and **security**
*    Can you **please** paste a sample here, at the root configuration node for NWEBSEC with all security enabled but HTTPS disabled. *targeting 4.6 runtime for ASP MVC, syste.web.mvc version 5.3

**Comment by klings** [comment]
Well, the dynamic ip filter in IIS is a security measure on its own, and there's no relation to NWebsec. You'll have to sort out those issues independently of NWebsec. Were you thinking of suggesting ip-filtering capabilities for NWebsec?

Yes, the link I provided is the minimal amount of config needed to get the NWebsec HttpModule added to the pipeline, and to be able to configure it. There's also some config to get rid of version headers. NWebsec will not do anything for your application unless you specifically enable specific features.

A good starting point is [Getting started](https://docs.nwebsec.com/en/4.2/nwebsec/getting-started.html). That shouldn't break most apps.

If you want to take it a step further, you'll have to enable HTTPS and serve the HTTPS related headers. You can also use CSP, but there's no one-size-fits-all CSP configuration, you'll have to tailor that to your app.

As for your bullet points:
* Your site should be accessible, but also secure. There's no conflict between security and accessibility, you can achieve both.
* The only sample I can provide is the "getting started" one. Anything more would require HTTPS, or CSP which must be tailored to your app.

A final note, if you want to build a secure app you'll have to run it over HTTPS. All bets are off when you let your users communicate in cleartext.
