### ISSUE TITLE
Subresource Integrity

### ISSUE THREAD

**Issue by RehanSaeed** [NWebsec/NWebsec#73]
Any plans to implement some kind of SRI HTML helper? https://scotthelme.co.uk/subresource-integrity/

**Comment by klings** [comment]
No, no plans to implement that since it's a standalone attribute.

**Comment by bkqc** [comment]
Could a way of automating this be to include a reference to a local copy of the file so the hash could be dynamically generated? Maybe it is not useful but just braintorming ;)
