### ISSUE TITLE
Suggestion: add "data:" as extension method on ImageSources

### ISSUE THREAD

**Issue by vindberg** [NWebsec/NWebsec#74]
I realize (after some searching) that is can be added using .CustomSources("data:") however it would benefit the discovery process if added as an extension method on ImageSources or the default.

Thanks for a great library.

**Comment by klings** [comment]
Thank you for the kind feedback, and thanks for star number 100!

The configurations types are reused for most CSP directives, so though it *might* be safe to allow data URIs for images (I'm not 100% sure), such a change would also encourage the use of data: for other directives which would be bad. The CSP spec specifically [warns against data URIs](http://www.w3.org/TR/CSP2/), and my advice is to avoid them altogether just in case.

Note that images can be injected into the page when allowing data uris, which might be bad enough depending on the circumstances. So I hope you can get by with CustomSources if you really, really need to include images as data URIs

**Comment by vindberg** [comment]
Hi, thanks for clearing that up.

I guess it would be safe to allow my own css files to use data URIs? How can that be enabled using your library? It doesn't work if added to the style directive?
```
.StyleSources(s => s.Self().CustomSources("data:")
```

**Comment by klings** [comment]
IIRC a co-worker ran into some issues there, FF and Chrome behaved differently for those. One would happily render the image from the css, but the other required data: added to img-src as well. I'm not sure what the preferred behaviour would be, but this is a bug in one of them. I'm not sure how it would work for Safari and Edge, they're both CSP 1.0, so I'd test there too. We ended up loading the image the old fashioned way to avoid any trouble.
