### ISSUE TITLE
NWebSec and Glimpse

### ISSUE THREAD

**Issue by monotore** [NWebsec/NWebsec#75]
Applying content security policy when using Glimpse has some issues as described here https://github.com/Glimpse/Glimpse/issues/631

A workaround was provided, but the link https://nwebsec.codeplex.com/wikipage?title=CSP%20and%20Glimpse is now broken. It would be great to know more about the workaround.

**Comment by klings** [comment]
The Internet never forgets. :)

https://nwebsec.codeplex.com/wikipage?title=CSP%20and%20Glimpse&version=2

**Comment by klings** [comment]
Which versions are you on? Are you on the new bleeding edge stuff?

**Comment by monotore** [comment]
Latest stable: NWebSec 4.2.0 and Glimpse.Mvc5 1.5.3

**Comment by monotore** [comment]
The workaround does not solve issues with inline style usage in the HTML injected by Glimpse Heads-Up Display.

**Comment by klings** [comment]
You can keep track of the Glimpse issue here: Glimpse/Glimpse.Prototype#88. I hope they'll make som adjustments to Glimpse so it's once again CSP friendly.
