### ISSUE TITLE
Trying to use in Classic Mode with IIS 8.5

### ISSUE THREAD

**Issue by solidstore** [NWebsec/NWebsec#76]
I am trying to use NWebSec (4.1 or 4.2) with IIS 8.5 running in classic mode. I believe I've followed the installation steps correctly. I have remove the module from the system.webServer section and add it to the system.web\httpModules as per the docs but the code still seems to require integrated pipeline mode. I'm using .NET 4.5

Any advise?

This is the exception is receive:

2015-11-27 12:59:55,063 ERROR [12  ] Web.Global                               Error:  Exception: System.PlatformNotSupportedException
Message: This operation requires IIS integrated pipeline mode.
Source: System.Web
   at System.Web.HttpResponse.get_Headers()
   at NWebsec.Helpers.HeaderResultHandler.HandleHeaderResult(HttpResponseBase response, HeaderResult result)
   at NWebsec.Helpers.ConfigurationHeaderSetter.SetSitewideHeadersFromConfig(HttpContextBase context)
   at NWebsec.Modules.HttpHeaderSecurityModule.AppBeginRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by klings** [comment]
Oh, I have to admit that this hasn't been specifically tested for quite some time. This still hangs around in the docs since it's been there since the very start of NWebsec. Any chance you could switch to the integrated pipeline?

**Comment by solidstore** [comment]
Unfortunately I'm working with a large enterprise web application that has many dependencies on Classic mode. Do you think there would be a lot of work to modify the modules to working within classic mode?

Also, is it possible with NWebSec, to define different CSP headers on a per-page basis?

**Comment by klings** [comment]
Oh, ok. IIRC I moved off a deprecated method to set the headers some time ago, but I'll have to investigate. I'll have a look when I've gotten the vnext packages out the door.

If you're running MVC, the MVC attributes will let you configure headers per controller/action. If you're using webforms or webpages, the only way to tweak the configuration for different pages/paths would be through either a location element in web.config, or the classic sub-web.config files for particular directories.

**Comment by klings** [comment]
Hi again, I dug into this a bit and this became a problem with the updates in NWebsec v3. Breaking changes in ASP.NET forced NWebsec over to the new API for setting http headers, which in turn broke classic mode. This went unnoticed on my part.

Unfortunately, the only option would be to try NWebsec v2 for your "classic" application. I've updated the [docs](https://docs.nwebsec.com/en/aspnet4/nwebsec/Configuration.html#classic-pipeline) to clarify this.
