### ISSUE TITLE
Chrome requires 'allow-modals' on 'sandbox' CSP element

### ISSUE THREAD

**Issue by smithc** [NWebsec/NWebsec#77]
Please see this sample for chrome: https://googlechrome.github.io/samples/block-modal-dialogs-sandboxed-iframe/

Unfortunately, Chrome will block modal dialogs by default, and the only way to override this behavior is by specifying 'allow-modals' on the sandbox attribute.

In order to support this, NWebSec needs to expose 'allow-modals' in configuration.

**Comment by klings** [comment]
The latest version of the standard lists:

allow-forms, allow-modals, allow-orientation-lock, allow-pointer-lock, allow-popups, allow-popups-to-escape-sandbox, allow-presentation, allow-same-origin, allow-scripts, and allow-top-navigation.

**Comment by klings** [comment]
Released.
