### ISSUE TITLE
Adding sources with additional calls?

### ISSUE THREAD

**Issue by damccull** [NWebsec/NWebsec#78]
Currently I'm doing something like this:
```csharp
app.UseCsp(options => {
                        options.DefaultSources(directive => directive.Self())
                                     .ImageSources(directive => directive.Self().CustomSources("*"))
                                     .ScriptSources(directive => directive.Self().UnsafeInline())
                                     .StyleSources(directive => directive.Self().UnsafeInline());
                        
                    });
```

I want to add some extra directives to the options object without overwriting what's already there from another method. Is that possible to do something like this without removing what's already in the headers?

```csharp
app.UseCsp(options => {
                        options.DefaultSources(directive => directive.Self())
                                     .ImageSources(directive => directive.Self().CustomSources("*"))
                                     .ScriptSources(directive => directive.Self().UnsafeInline())
                                     .StyleSources(directive => directive.Self().UnsafeInline());

                        options.DefaultSources(directive=>"https://some.other.url");
                        
                    });
```

**Comment by klings** [comment]
Yes, that should work. `app.UseCsp(...)` will hand you a new instance of the options with new directives, so configuring the directives can be done in separate/multiple steps. That last statement is invalid, the following example should work. Feel free to reopen the issue if you run into trouble.

    app.UseCsp(options =>
    {
        options
        .DefaultSources(directive => directive.Self())
        .ImageSources(directive => directive.Self().CustomSources("*"))
        .ScriptSources(directive => directive.Self().UnsafeInline())
        .StyleSources(directive => directive.Self().UnsafeInline());

        options.DefaultSources(directive => directive.CustomSources("https://some.other.url"));

    });
