### ISSUE TITLE
Update headers in action without Attributes (runtime)

### ISSUE THREAD

**Issue by runes83** [NWebsec/NWebsec#79]
Is it possible to set/update for example x-frameancestor csp directive in the action kode (MVC) ?
We need to set the frame domain pr session so wondering how to do that ?

**Comment by klings** [comment]
No, there's currently no way to do that. There are a few that have asked about dynamic configuration during runtime, so I have it on my radar. I'll have a look at it after the work with ASP.NET Core is done.
