### ISSUE TITLE
CSP nonce does not work in safari

### ISSUE THREAD

**Issue by runes83** [NWebsec/NWebsec#80]
Is it possible to be able to turn of unsafe inline, only for browsers that does not support nonce for inline scripts? Safari does not support this, but I don't want to turn on unsafe-inline for every browser.

**Comment by klings** [comment]
The idea is to combine the nonce with the unsafe-inline directive. If the UA supports nonces, the 'unsafe-inline' source will be ignored, and all scripts will be checked for the nonce. Safari, in this case, would not be able to make any sense of the nonce but would pick up 'unsafe-inline'. This is a trick to make the introduction of the nonces backwards compatible.
