### ISSUE TITLE
Unable to find extension method CspScriptNonce for IHtmlHelper<dynamic>

### ISSUE THREAD

**Issue by SeeWhat** [NWebsec/NWebsec#84]
When trying to use AspNetCore.MVC Helper [CspScriptNonce ](https://github.com/NWebsec/NWebsec/blob/master/src/NWebsec.AspNetCore.Mvc/HttpHeaders/Csp/CspHtmlHelpers.cs#L17) as below I get the error as shown

`<script type="text/javascript" @Html.CspScriptNonce()>...</script>`

> 'IHtmlHelper<MyModel>' does not contain a definition for 'CspScriptNonce' and the best extension method overload 'CspHtmlHelpers.CspScriptNonce(IHtmlHelper<dynamic>)' requires a receiver of type 'IHtmlHelper<dynamic>'

Note that I'm using a strongly typed model `@model MyModelClass` vs `@Model MyModelClass`

**Comment by SeeWhat** [comment]
Was casting in a helper method and missed its type is actually different

**Comment by klings** [comment]
The taghelpers have been updated. In the upcoming version you can add `nws-csp-add-nonce="true"` to script or style tags. You'll also get intellisense in the next version.
