### ISSUE TITLE
Proper capitalization of includeSubDomains directive in HSTS

### ISSUE THREAD

**Issue by jozefizso** [NWebsec/NWebsec#86]
NWebSec will generate `Strict-Transport-Security` header with `includeSubdomains` directive. According to validator at https://hstspreload.appspot.com the proper capitalization for this directive is `includeSubDomains`.

NWebSec should be updated to have proper capitalization of this directive for both `Strict-Transport-Security` and `Public-Key-Pins` headers.

https://wiki.mozilla.org/Security/Guidelines/Web_Security

```
Strict-Transport-Security: max-age=2592000; includeSubdomains

Warning: Non-standard capitalization of includeSubDomains
Header contains the token `includeSubdomains`. The recommended capitalization is `includeSubDomains`.
```

**Comment by klings** [comment]
That's amazing! I'll get this fixed in the next release. :)

I assume this was not blocking in any way, just a warning?

>

**Comment by jozefizso** [comment]
It just a warning. I could not find if any browser will ignore the miscapitalized directive.

**Comment by klings** [comment]
Same thing for HPKP, so fixed that too.
