### ISSUE TITLE
problem for UpgradeInsecureRequests, changes

### ISSUE THREAD

**Issue by kanpinar** [NWebsec/NWebsec#92]
I want to use another project for api 
on local its working on http://localhost:54652

with
.UpgradeInsecureRequests(sslPort.HasValue ? sslPort.Value : 443)
When i called XMLHttpRequest to this **http**://localhost:54652 changes **https**://localhost:54652

I think exeptions needed for UpgradeInsecureRequests

**Comment by klings** [comment]
The upgrade-insecure-requests CSP directive was created to help legacy web apps switch to https, by changing requests triggered by a web page from http to https. Don't enable it unless you want all your requests upgraded to https.
